import React from 'react'
import Link from 'next/link'

const glossaryTerms = {
  'whale': { term: 'Whale', definition: 'A whale is an individual or entity that holds a very large amount of cryptocurrency. In Bitcoin, a whale typically holds 1,000+ BTC. In Ethereum, a whale might hold 10,000+ ETH. Whale movements are closely watched because their large transactions can significantly impact market prices. When a whale buys or sells, it can trigger cascading price movements as other traders react. Sonar Tracker monitors whale wallets across 10+ blockchains to give traders early detection of these market-moving transactions.', related: ['accumulation', 'distribution', 'smart-money', 'whale-alert'] },
  'accumulation': { term: 'Accumulation', definition: 'Accumulation is the process of gradually buying and holding a cryptocurrency over time, typically by whales or institutions. During accumulation phases, large wallets steadily increase their holdings without causing dramatic price spikes. This is often done through multiple smaller purchases rather than one large buy. On Sonar Tracker, net positive inflows to whale wallets indicate accumulation. Identifying accumulation early can signal that informed money expects future price appreciation.', related: ['whale', 'distribution', 'smart-money', 'net-inflow'] },
  'distribution': { term: 'Distribution', definition: 'Distribution is the opposite of accumulation: it occurs when whales or institutions gradually sell their holdings. During distribution, large holders reduce their positions over time, often through strategic selling to minimize price impact. Net negative outflows from whale wallets on Sonar Tracker indicate distribution. Recognizing distribution patterns can help traders avoid buying into selling pressure from informed large holders.', related: ['accumulation', 'whale', 'net-outflow', 'sell-pressure'] },
  'on-chain-analysis': { term: 'On-Chain Analysis', definition: 'On-chain analysis is the study of blockchain data to understand market dynamics and predict price movements. Unlike traditional technical analysis which only looks at price charts, on-chain analysis examines actual transaction data: wallet balances, transaction volumes, exchange flows, whale movements, and smart contract interactions. Sonar Tracker specializes in on-chain analysis by monitoring whale transactions across multiple blockchains and using AI to classify and interpret the data.', related: ['whale', 'blockchain', 'transaction-hash', 'block-explorer'] },
  'smart-money': { term: 'Smart Money', definition: 'Smart money refers to capital controlled by institutional investors, market experts, or experienced traders who consistently outperform the market. In crypto, smart money wallets are those with a proven track record of buying before pumps and selling before dumps. Sonar Tracker\'s whale tracking helps identify smart money movements by analyzing transaction patterns, timing, and wallet history. Following smart money is a strategy that attempts to replicate the trades of these informed actors.', related: ['whale', 'institutional-investor', 'accumulation'] },
  'front-running': { term: 'Front-Running', definition: 'Front-running in crypto occurs when a trader sees a pending large transaction in the mempool and places their own transaction ahead of it to profit from the expected price impact. For example, if a whale\'s pending buy order for $5M of ETH is visible in the mempool, a front-runner might buy ETH first, then sell after the whale\'s order pushes the price up. MEV bots automate this process. Sonar Tracker helps detect potential front-running by monitoring large pending transactions.', related: ['mempool', 'mev', 'sandwich-attack', 'whale'] },
  'mempool': { term: 'Mempool', definition: 'The mempool (memory pool) is a waiting area for unconfirmed blockchain transactions. When you send a crypto transaction, it first enters the mempool before being included in a block by miners or validators. Monitoring the mempool reveals pending whale transactions before they are confirmed, giving traders an early signal. Large transactions waiting in the mempool can indicate imminent price movements once they are processed.', related: ['front-running', 'mev', 'transaction-hash', 'gas-fee'] },
  'wash-trading': { term: 'Wash Trading', definition: 'Wash trading is a form of market manipulation where a trader simultaneously buys and sells the same asset to create artificial volume. In crypto, wash trading inflates a token\'s apparent trading volume to make it seem more liquid or popular than it actually is. Sonar Tracker\'s risk assessment features help detect wash trading patterns by analyzing transaction clustering, unusual volume spikes, and wallet relationships.', related: ['market-manipulation', 'pump-and-dump', 'whale'] },
  'whale-alert': { term: 'Whale Alert', definition: 'A whale alert is a notification triggered when a large cryptocurrency transaction occurs. These alerts typically track transactions above a certain USD threshold (e.g., $500K+). Sonar Tracker provides whale alerts as part of its Pro plan, tracking transactions over $10K with AI-powered buy/sell classification. Unlike basic whale alert services that just show raw data, Sonar classifies each transaction and provides context about what the movement means.', related: ['whale', 'on-chain-analysis', 'smart-money'] },
  'gas-fee': { term: 'Gas Fee', definition: 'Gas fees are transaction costs paid to blockchain validators for processing transactions. On Ethereum, gas is measured in Gwei and varies based on network demand. High gas fees during whale transactions can indicate urgency — a whale willing to pay premium gas typically wants their transaction processed immediately, which may signal time-sensitive trading decisions. Monitoring gas expenditure patterns provides additional context for whale movement analysis.', related: ['mempool', 'transaction-hash', 'blockchain'] },
  'net-inflow': { term: 'Net Inflow', definition: 'Net inflow measures the difference between cryptocurrency entering and leaving a particular wallet, address, or exchange. Positive net inflow to a whale wallet means the wallet is accumulating more than it is selling. Positive net inflow to exchanges typically signals selling pressure, as traders move crypto to exchanges to sell. Sonar Tracker displays net inflow data on its dashboard to help traders identify accumulation and distribution patterns in real-time.', related: ['accumulation', 'net-outflow', 'exchange-flow'] },
  'net-outflow': { term: 'Net Outflow', definition: 'Net outflow is when more cryptocurrency leaves a wallet or exchange than enters it. Exchange net outflow (more crypto leaving exchanges than entering) is generally considered bullish, as it suggests holders are moving to cold storage for long-term holding rather than selling. Whale wallet net outflow indicates distribution. Sonar Tracker tracks both exchange flows and individual whale wallet flows to provide a complete picture.', related: ['distribution', 'net-inflow', 'exchange-flow', 'cold-wallet'] },
  'exchange-flow': { term: 'Exchange Flow', definition: 'Exchange flow tracks cryptocurrency moving into and out of centralized exchanges. Large inflows to exchanges often signal selling intent, as traders deposit crypto to exchanges to sell. Large outflows suggest buying and holding, as traders withdraw to self-custody wallets. Exchange flow is one of the most watched on-chain metrics because it directly relates to supply and demand dynamics on order books.', related: ['net-inflow', 'net-outflow', 'accumulation', 'distribution'] },
  'transaction-hash': { term: 'Transaction Hash', definition: 'A transaction hash (txn hash or tx hash) is a unique identifier for a blockchain transaction. It is a string of characters generated by hashing the transaction data. Every on-chain transaction has a unique hash that can be used to look it up on block explorers like Etherscan. Sonar Tracker provides transaction hashes for every whale transaction it tracks, allowing users to verify and investigate specific movements directly on the blockchain.', related: ['block-explorer', 'blockchain', 'on-chain-analysis'] },
  'block-explorer': { term: 'Block Explorer', definition: 'A block explorer is a tool that allows anyone to search and browse blockchain data including transactions, wallet addresses, blocks, and smart contracts. Examples include Etherscan (Ethereum), BscScan (BSC), and PolygonScan (Polygon). Sonar Tracker aggregates data from multiple block explorers and enriches it with AI classification, whale scoring, and sentiment analysis to provide actionable intelligence rather than raw data.', related: ['transaction-hash', 'blockchain', 'on-chain-analysis'] },
  'blockchain': { term: 'Blockchain', definition: 'A blockchain is a distributed, immutable digital ledger that records transactions across a network of computers. Each block contains a batch of verified transactions and is cryptographically linked to the previous block. Blockchains enable trustless, transparent transactions without intermediaries. Sonar Tracker monitors transactions across Ethereum, Bitcoin, Tron, Polygon, Avalanche, BSC, Arbitrum, Optimism, and other major blockchains.', related: ['block-explorer', 'transaction-hash', 'gas-fee'] },
  'market-manipulation': { term: 'Market Manipulation', definition: 'Market manipulation in crypto includes practices like pump-and-dump schemes, wash trading, spoofing, and coordinated whale selling to trigger cascading liquidations. Because crypto markets are less regulated than traditional markets, manipulation is more common. On-chain analysis through tools like Sonar Tracker helps detect manipulation by identifying unusual transaction patterns, coordinated wallet movements, and artificial volume spikes.', related: ['wash-trading', 'pump-and-dump', 'whale', 'front-running'] },
  'pump-and-dump': { term: 'Pump and Dump', definition: 'A pump and dump is a market manipulation scheme where insiders accumulate a token cheaply, artificially inflate its price through coordinated buying and promotion, then sell their holdings at the peak to unsuspecting buyers. The price then crashes. Sonar Tracker helps identify potential pump-and-dump patterns by flagging sudden whale accumulation followed by aggressive social promotion and unusual volume patterns.', related: ['market-manipulation', 'whale', 'wash-trading'] },
  'cold-wallet': { term: 'Cold Wallet', definition: 'A cold wallet is a cryptocurrency storage method that is not connected to the internet. Cold wallets include hardware wallets (like Ledger and Trezor) and paper wallets. When whales move crypto from exchanges to cold wallets, it typically signals long-term holding intent and reduces selling pressure. Tracking cold wallet movements is an important part of on-chain analysis.', related: ['hot-wallet', 'exchange-flow', 'accumulation'] },
  'hot-wallet': { term: 'Hot Wallet', definition: 'A hot wallet is a cryptocurrency wallet connected to the internet, making it convenient for frequent transactions but more vulnerable to hacking. Exchange wallets are hot wallets. When crypto moves from cold storage to hot wallets (especially exchange hot wallets), it can signal intent to trade or sell in the near term. Monitoring hot wallet inflows is a key whale tracking metric.', related: ['cold-wallet', 'exchange-flow', 'distribution'] },
  'mev': { term: 'MEV (Maximal Extractable Value)', definition: 'MEV refers to the maximum value that can be extracted from block production beyond standard block rewards and gas fees. MEV extraction includes front-running, sandwich attacks, and arbitrage. MEV bots monitor the mempool for profitable opportunities and can impact the execution price of whale trades. Understanding MEV helps traders account for the real cost and impact of large on-chain transactions.', related: ['front-running', 'sandwich-attack', 'mempool', 'gas-fee'] },
  'sandwich-attack': { term: 'Sandwich Attack', definition: 'A sandwich attack is a type of MEV extraction where a bot places a buy order before and a sell order after a large pending transaction. The attacker profits from the price impact of the victim\'s trade. For example, a bot sees a large pending DEX swap, buys the token first (pushing the price up), lets the victim buy at a higher price, then sells immediately after for profit. Whale transactions on DEXs are common targets.', related: ['mev', 'front-running', 'mempool'] },
  'institutional-investor': { term: 'Institutional Investor', definition: 'An institutional investor is an organization that invests large amounts of capital — hedge funds, pension funds, endowments, venture capital firms, and family offices. In crypto, institutional investors include firms like Grayscale, MicroStrategy, and various crypto-focused hedge funds. Their transactions are typically large enough to qualify as whale activity and can significantly influence market direction.', related: ['whale', 'smart-money', 'accumulation'] },
  'sell-pressure': { term: 'Sell Pressure', definition: 'Sell pressure refers to the aggregate selling activity in a market. High sell pressure occurs when many holders (especially whales) are selling or moving crypto to exchanges. On-chain indicators of sell pressure include rising exchange inflows, negative net whale flows, and increasing distribution patterns. Sonar Tracker\'s sentiment analysis factors in sell pressure to generate Bullish/Neutral/Bearish ratings for each token.', related: ['distribution', 'exchange-flow', 'net-outflow'] },
  'defi': { term: 'DeFi (Decentralized Finance)', definition: 'DeFi is a financial ecosystem built on blockchain smart contracts that provides services like lending, borrowing, trading, and yield farming without traditional intermediaries. DeFi protocols include Uniswap, Aave, Compound, and MakerDAO. Whale activity in DeFi protocols is tracked by Sonar as DEFI transaction types. Large DeFi movements can indicate sophisticated strategies like yield farming, liquidity provision, or leveraged trading.', related: ['dex', 'yield-farming', 'liquidity', 'smart-contract'] },
  'dex': { term: 'DEX (Decentralized Exchange)', definition: 'A DEX is a cryptocurrency exchange that operates without a central authority, using smart contracts to facilitate trading directly between users. Examples include Uniswap, SushiSwap, and PancakeSwap. DEX trades are recorded on-chain and visible to whale trackers. Large DEX swaps by whales can significantly impact token prices through slippage, making DEX whale monitoring especially valuable for traders.', related: ['defi', 'liquidity', 'smart-contract', 'slippage'] },
  'slippage': { term: 'Slippage', definition: 'Slippage is the difference between the expected price of a trade and the actual execution price. In crypto, slippage occurs when large orders move the market due to insufficient liquidity. Whale trades often experience significant slippage, especially on DEXs. Understanding slippage is important when evaluating the true cost and impact of whale transactions tracked on Sonar.', related: ['dex', 'liquidity', 'whale'] },
  'liquidity': { term: 'Liquidity', definition: 'Liquidity refers to how easily an asset can be bought or sold without significantly affecting its price. High liquidity means large orders can be filled with minimal price impact. Low liquidity means even moderate sells can crash the price. Whale trackers monitor liquidity because whale movements in low-liquidity tokens can cause extreme price swings.', related: ['slippage', 'dex', 'market-manipulation'] },
  'smart-contract': { term: 'Smart Contract', definition: 'A smart contract is a self-executing program stored on a blockchain that automatically enforces the terms of an agreement. Smart contracts power DeFi protocols, NFT marketplaces, and token standards. Whale interactions with smart contracts can indicate strategies like yield farming, providing liquidity, or participating in governance. Sonar tracks whale smart contract interactions as DEFI transaction types.', related: ['defi', 'dex', 'blockchain'] },
  'token-burn': { term: 'Token Burn', definition: 'Token burning is the permanent removal of tokens from circulation by sending them to an inaccessible wallet address. Burns reduce total supply, which can increase per-token value. Whale-initiated burns or large protocol burns are significant on-chain events tracked by Sonar. A project burning tokens is generally seen as a deflationary and value-accruing action.', related: ['smart-contract', 'blockchain', 'defi'] },
  'yield-farming': { term: 'Yield Farming', definition: 'Yield farming is a DeFi strategy where users deposit crypto into liquidity pools or lending protocols to earn returns. Yield farmers earn fees from trading activity (on DEXs) or interest from borrowers (on lending platforms). Whale yield farming activity is visible on-chain when large wallets deposit significant sums into DeFi protocols, which Sonar classifies as DEFI transactions.', related: ['defi', 'liquidity', 'smart-contract', 'dex'] },
  'layer-2': { term: 'Layer 2', definition: 'Layer 2 (L2) solutions are protocols built on top of a base blockchain (Layer 1) to improve scalability and reduce transaction costs. Examples include Arbitrum, Optimism, and Polygon for Ethereum. Whale activity on L2 networks is increasingly important as more trading volume moves to these cheaper, faster networks. Sonar monitors whale transactions on major L2s alongside main chains.', related: ['blockchain', 'gas-fee', 'rollup'] },
  'rollup': { term: 'Rollup', definition: 'A rollup is a specific type of Layer 2 scaling solution that bundles (rolls up) multiple transactions into one batch submitted to the main chain. Optimistic Rollups (Optimism, Arbitrum) and ZK-Rollups (zkSync, StarkNet) are the two main types. Rollups significantly reduce gas costs, making them attractive for large whale transactions where gas savings scale with transaction size.', related: ['layer-2', 'gas-fee', 'blockchain'] },
  'airdrop': { term: 'Airdrop', definition: 'An airdrop is a distribution of free cryptocurrency tokens to wallet holders, typically used by new projects to build community and awareness. Airdrops can be based on holding a specific token, interacting with a protocol, or meeting other criteria. Whale wallets receiving airdrops of a new token can signal project legitimacy and institutional interest. On Sonar Tracker, large airdrop claim transactions are classified and tracked, helping traders identify which new tokens are attracting whale attention. Monitoring airdrop activity is useful for discovering early-stage projects that smart money considers valuable.', related: ['token-burn', 'governance-token', 'defi'] },
  'staking': { term: 'Staking', definition: 'Staking involves locking cryptocurrency in a blockchain network to help validate transactions and earn rewards. In Proof-of-Stake networks like Ethereum, validators must stake tokens as collateral. When whales stake large amounts, it reduces circulating supply and signals long-term confidence in the network. Conversely, large unstaking events can precede sell pressure as tokens become liquid again. Sonar Tracker monitors staking-related whale movements to help traders anticipate supply changes. The staking yield and the amount staked by whales are important on-chain metrics for assessing network health and token value.', related: ['defi', 'yield-farming', 'accumulation', 'smart-contract'] },
  'liquidity-mining': { term: 'Liquidity Mining', definition: 'Liquidity mining is a DeFi mechanism where users deposit token pairs into decentralized exchange pools and earn reward tokens in return. It incentivizes liquidity providers to create deep markets for trading. Whale participation in liquidity mining moves large amounts of capital on-chain, making these transactions visible on Sonar Tracker as DEFI-classified activities. When whales enter or exit liquidity mining positions, it can significantly impact token prices through the addition or removal of liquidity. Tracking whale liquidity mining activity provides insight into which protocols and token pairs attract institutional-grade capital.', related: ['yield-farming', 'defi', 'dex', 'impermanent-loss'] },
  'impermanent-loss': { term: 'Impermanent Loss', definition: 'Impermanent loss occurs when the price ratio of tokens in a liquidity pool changes compared to when they were deposited, resulting in a loss relative to simply holding the tokens. The loss becomes permanent only when the liquidity provider withdraws. Whales managing large DeFi positions must account for impermanent loss risk, and their decisions to add or remove liquidity based on this risk are visible as on-chain transactions. Monitoring whale exits from liquidity pools on Sonar can indicate that large players expect significant price divergence between paired tokens.', related: ['liquidity-mining', 'dex', 'defi', 'slippage'] },
  'governance-token': { term: 'Governance Token', definition: 'A governance token grants holders voting rights on protocol decisions such as fee structures, treasury allocation, and upgrade proposals. Examples include UNI (Uniswap), AAVE (Aave), and COMP (Compound). Whale accumulation of governance tokens can signal intent to influence protocol direction or expectation of value appreciation from upcoming governance decisions. Sonar Tracker classifies governance token transactions and tracks whale voting power concentration, giving traders insight into which protocols may see significant governance-driven changes.', related: ['utility-token', 'defi', 'smart-contract', 'accumulation'] },
  'utility-token': { term: 'Utility Token', definition: 'A utility token provides access to a specific product or service within a blockchain ecosystem. Unlike governance tokens which grant voting rights, utility tokens are spent or consumed to use platform features. Examples include LINK (used to pay Chainlink oracle operators) and FIL (used to pay for Filecoin storage). Whale purchases of utility tokens often indicate expected increased usage of the underlying platform. Sonar tracks utility token whale activity to help traders identify growing ecosystems before usage metrics become publicly evident.', related: ['governance-token', 'smart-contract', 'defi'] },
  'wrapped-token': { term: 'Wrapped Token', definition: 'A wrapped token is a cryptocurrency pegged 1:1 to another asset but issued on a different blockchain. WBTC (Wrapped Bitcoin on Ethereum) and WETH (Wrapped Ether) are common examples. Wrapping allows tokens to be used in DeFi ecosystems on chains where the native asset does not exist. Large wrapping and unwrapping transactions by whales are tracked on Sonar Tracker and can indicate cross-chain capital flows. A surge in WBTC minting, for example, suggests Bitcoin holders are moving capital into Ethereum DeFi.', related: ['bridge', 'defi', 'blockchain', 'token-flow'] },
  'bridge': { term: 'Bridge', definition: 'A blockchain bridge is a protocol that enables transferring assets between different blockchain networks. Bridges lock tokens on the source chain and mint equivalent tokens on the destination chain. Whale bridge transactions are significant because they reveal cross-chain capital flows — large movements from Ethereum to Arbitrum, for example, may indicate whales chasing better yields or preparing for a new protocol launch. Sonar Tracker monitors bridge-related whale activity across major bridges to surface these cross-chain signals.', related: ['wrapped-token', 'layer-2', 'blockchain', 'exchange-flow'] },
  'flash-loan': { term: 'Flash Loan', definition: 'A flash loan is an uncollateralized loan that must be borrowed and repaid within a single blockchain transaction. If the borrower fails to repay within the same transaction, the entire operation reverts as if it never happened. Flash loans enable complex arbitrage, liquidation, and collateral swaps without requiring upfront capital. While flash loan transactions are technically not whale activity in the traditional sense, they can move massive amounts of capital and cause sudden price dislocations. Sonar flags unusual transaction volumes that may indicate flash loan arbitrage activity.', related: ['defi', 'smart-contract', 'mev', 'slippage'] },
  'rug-pull': { term: 'Rug Pull', definition: 'A rug pull is a crypto scam where project developers suddenly remove liquidity or abandon a project after raising funds from investors, causing the token price to collapse to near zero. Common rug pull patterns include developers draining DEX liquidity pools, dumping pre-mined tokens, or disabling sell functions in smart contracts. Sonar Tracker risk assessment features help detect potential rug pulls by flagging tokens where developer wallets show suspicious withdrawal patterns, rapid liquidity removal, or concentrated holder distribution.', related: ['market-manipulation', 'pump-and-dump', 'liquidity', 'defi'] },
  'bull-trap': { term: 'Bull Trap', definition: 'A bull trap is a false market signal that suggests a declining price trend has reversed upward, luring buyers in before the price resumes its downward trajectory. Bull traps often occur after a brief price rally during a broader downtrend, trapping optimistic buyers at higher prices. Whale tracking can help identify bull traps: if a price rally is not supported by genuine whale accumulation or is accompanied by whale distribution, it may be a bull trap. Sonar Tracker sentiment analysis combines price action with whale flow data to assess signal reliability.', related: ['bear-trap', 'market-manipulation', 'sell-pressure', 'distribution'] },
  'bear-trap': { term: 'Bear Trap', definition: 'A bear trap is a false signal indicating an uptrend has reversed downward, causing traders to sell or short before the price continues higher. Bear traps shake out weak holders and allow whales to accumulate at lower prices. On-chain evidence of a bear trap includes whale buying during apparent breakdowns and increasing accumulation despite negative price action. Sonar Tracker helps identify bear traps by showing when whale behavior contradicts what price charts suggest — whales buying heavily while prices appear to be falling is a classic bear trap indicator.', related: ['bull-trap', 'accumulation', 'smart-money', 'stop-hunt'] },
  'dead-cat-bounce': { term: 'Dead Cat Bounce', definition: 'A dead cat bounce is a temporary, short-lived recovery in price during a prolonged decline. The term comes from the idea that even a dead cat will bounce if dropped from a high enough point. In crypto, dead cat bounces often occur after sharp sell-offs as bargain hunters or automated trading bots briefly push prices higher. Distinguishing a dead cat bounce from a genuine reversal requires analyzing whale behavior: if whales continue distributing during the bounce, it is likely a dead cat bounce rather than a recovery. Sonar Tracker whale flow data provides this critical context.', related: ['bull-trap', 'distribution', 'sell-pressure'] },
  'support-level': { term: 'Support Level', definition: 'A support level is a price point where buying pressure historically prevents further price decline. Support levels form because traders and whales view these prices as attractive entry points. In on-chain analysis, support can also be identified by looking at price levels where large whale wallets accumulated their positions — whales often defend these levels to protect their investment. Sonar Tracker token analytics show historical whale entry prices, helping traders identify on-chain support levels that complement traditional chart analysis.', related: ['resistance-level', 'breakout', 'accumulation'] },
  'resistance-level': { term: 'Resistance Level', definition: 'A resistance level is a price point where selling pressure historically prevents further price increase. Resistance forms at prices where previous buyers look to exit at breakeven or profit. In whale tracking context, resistance can be identified at price levels where whale distribution historically occurs. Sonar Tracker analytics reveal where whales tend to sell, providing on-chain resistance data that goes beyond what traditional price charts show. When whale selling clusters at specific price levels, those levels are likely to act as resistance.', related: ['support-level', 'breakout', 'distribution', 'sell-pressure'] },
  'breakout': { term: 'Breakout', definition: 'A breakout occurs when a price moves above a resistance level or below a support level with increased volume, signaling a potential new trend. Breakouts are most reliable when confirmed by on-chain data: a price breakout above resistance accompanied by whale accumulation and increasing buying pressure is more likely to sustain. False breakouts (where price briefly crosses a level then reverses) often lack whale participation. Sonar Tracker helps validate breakouts by showing real-time whale buying or selling activity around key price levels.', related: ['support-level', 'resistance-level', 'volume-profile'] },
  'volume-profile': { term: 'Volume Profile', definition: 'Volume profile is an advanced charting technique that displays the total trading volume at each price level over a specified period. Unlike standard volume bars that show volume over time, volume profile shows volume at price, revealing where the most trading activity occurred. In whale tracking, volume profile analysis combined with whale transaction data from Sonar reveals whether high-volume price levels are driven by whale activity or retail trading. Levels with concentrated whale volume tend to act as stronger support and resistance.', related: ['breakout', 'support-level', 'resistance-level', 'order-flow'] },
  'order-flow': { term: 'Order Flow', definition: 'Order flow analysis studies the real-time stream of buy and sell orders entering the market. In crypto, order flow on centralized exchanges shows the balance between buyers and sellers at each price level. Whale orders significantly impact order flow — a single whale market order can consume multiple price levels of liquidity. On-chain order flow (tracked by Sonar) complements exchange order books by showing when whales are moving capital to exchanges to sell, or withdrawing to accumulate. This combination provides a comprehensive view of market pressure.', related: ['volume-profile', 'exchange-flow', 'sell-pressure', 'liquidity'] },
  'dark-pool': { term: 'Dark Pool', definition: 'A dark pool is a private trading venue where large orders are matched without being visible on public order books. In traditional finance, dark pools exist to prevent large orders from moving markets. In crypto, OTC desks and some institutional platforms serve a similar function. While dark pool trades are harder to detect, the subsequent on-chain settlement of these trades is visible on blockchain explorers and Sonar Tracker. Large, oddly-sized transfers between known institutional wallets often indicate dark pool execution.', related: ['otc-trade', 'institutional-investor', 'whale', 'order-flow'] },
  'otc-trade': { term: 'OTC Trade', definition: 'An over-the-counter (OTC) trade is a direct transaction between two parties, typically facilitated by an OTC desk, without using a public exchange. OTC trades are preferred by whales and institutions because they avoid slippage and market impact from large orders. While OTC deals themselves happen off-chain, the settlement (moving tokens between wallets) is visible on-chain. Sonar Tracker identifies potential OTC settlements by flagging large direct transfers between institutional wallets that bypass exchange order books.', related: ['dark-pool', 'institutional-investor', 'whale', 'slippage'] },
  'stop-hunt': { term: 'Stop Hunt', definition: 'A stop hunt is a market manipulation technique where large players intentionally push prices past key levels to trigger clusters of stop-loss orders, then reverse direction to profit from the resulting liquidations. In crypto, whales may sell aggressively to push price below a support level, triggering stop-losses and cascading liquidations, then buy back at lower prices. Sonar Tracker helps identify potential stop hunts by flagging unusual whale selling followed by rapid re-accumulation at lower prices, a distinctive on-chain footprint.', related: ['market-manipulation', 'liquidation', 'bear-trap', 'whale'] },
  'liquidation': { term: 'Liquidation', definition: 'Liquidation occurs when a leveraged trading position is forcefully closed because the trader\'s margin is no longer sufficient to cover potential losses. In crypto, liquidations can cascade: as positions are liquidated, forced selling pushes prices lower, triggering more liquidations. Whale-induced price movements that trigger mass liquidations are visible in on-chain data as large sell volumes followed by rapid price recovery. Sonar Tracker monitors whale activity around known liquidation clusters to help traders avoid being caught in liquidation cascades.', related: ['stop-hunt', 'sell-pressure', 'support-level', 'market-manipulation'] },
  'hodl': { term: 'HODL', definition: 'HODL (Hold On for Dear Life) is a crypto strategy of holding assets through volatility without selling, based on long-term conviction. The term originated from a misspelling of "hold" in a 2013 Bitcoin forum post and became crypto culture. From a whale tracking perspective, HODL behavior is identified by wallets that consistently accumulate and never sell, even during crashes. Sonar Tracker identifies HODL whale wallets by their long-term holding patterns and classifies them separately from active trading wallets, providing insight into the conviction level of large holders.', related: ['accumulation', 'diamond-hands', 'cold-wallet', 'whale'] },
  'fud': { term: 'FUD', definition: 'FUD stands for Fear, Uncertainty, and Doubt — negative information (often misleading or exaggerated) spread to drive down asset prices. FUD can be organic (genuine bad news) or manufactured (deliberate manipulation to enable cheaper accumulation). Whale tracking provides critical context during FUD events: if whales are accumulating heavily while FUD is spreading, the negative narrative may be manufactured. Sonar Tracker sentiment analysis combines news FUD scoring with whale flow data to help traders distinguish between legitimate concerns and manipulative FUD campaigns.', related: ['fomo', 'market-manipulation', 'accumulation', 'smart-money'] },
  'fomo': { term: 'FOMO', definition: 'FOMO (Fear of Missing Out) is the anxiety that drives impulsive buying when prices are rising rapidly. FOMO-driven buying often occurs at local price tops, making it a costly emotional response. Whale behavior during FOMO events is telling: if whales are distributing (selling) while retail FOMO drives prices higher, it often signals an approaching reversal. Sonar Tracker helps traders counter FOMO by providing objective whale flow data — seeing that smart money is selling can override the emotional urge to buy into a rally.', related: ['fud', 'bull-trap', 'distribution', 'sell-pressure'] },
  'diamond-hands': { term: 'Diamond Hands', definition: 'Diamond hands refers to the resolve to hold a crypto position through extreme volatility and price declines without selling. The term contrasts with "paper hands" (selling at the first sign of decline). In whale tracking context, diamond hands wallets are those that maintained positions through major market crashes. These wallets represent the strongest conviction holders. Sonar Tracker identifies diamond hands whales by analyzing holding duration, behavior during past downturns, and resistance to sell during high-volatility periods.', related: ['hodl', 'paper-hands', 'accumulation', 'whale'] },
  'paper-hands': { term: 'Paper Hands', definition: 'Paper hands refers to selling assets quickly at the first sign of price decline or adverse news. In whale tracking, paper hands behavior among large holders signals potential cascading sell-offs — when whales with paper hands tendencies start selling, it often triggers further declines. Sonar Tracker whale scoring helps differentiate between strong-conviction whale wallets and those with a history of panic selling, allowing traders to weight whale signals based on the historical behavior patterns of individual large wallets.', related: ['diamond-hands', 'fud', 'distribution', 'sell-pressure'] },
  'market-maker': { term: 'Market Maker', definition: 'A market maker is an entity that provides liquidity to markets by continuously placing both buy and sell orders, profiting from the spread between them. In crypto, market makers range from algorithmic trading firms to DeFi protocols. Professional market makers move large volumes on-chain that are visible on Sonar Tracker. Their activity patterns differ from directional whale traders: market makers show balanced buy and sell volumes rather than accumulation or distribution patterns. Identifying market maker wallets helps separate noise from genuine directional whale signals.', related: ['liquidity', 'order-flow', 'exchange-flow', 'dark-pool'] },
  'token-flow': { term: 'Token Flow', definition: 'Token flow tracks the movement of tokens between wallets, exchanges, and DeFi protocols. Analyzing token flow reveals the full lifecycle of capital: from exchange withdrawal (buying) to holding in personal wallets, to DeFi protocol deposits (yield seeking), to exchange deposits (selling). Sonar Tracker visualizes token flow for tracked tokens, showing net directional movement across wallet categories. Aggregate token flow data — especially exchange inflows and outflows — is one of the most predictive on-chain metrics for short-term price direction.', related: ['exchange-flow', 'net-inflow', 'net-outflow', 'on-chain-analysis'] },
  'whale-score': { term: 'Whale Score', definition: 'A whale score is a numerical rating (typically 0-100) assigned to a wallet based on its transaction history, holdings size, trading frequency, and market influence. Higher whale scores indicate wallets with greater potential to move markets. Sonar Tracker calculates whale scores by analyzing factors including total transaction volume, number of large trades, portfolio diversity, historical accuracy of timing, and interactions with known institutional addresses. Traders use whale scores to prioritize which wallet movements to pay attention to — a transaction from a 95-score wallet is more significant than from a 30-score wallet.', related: ['whale', 'smart-money', 'institutional-investor', 'on-chain-analysis'] },
}

export async function generateMetadata({ params }) {
  const slug = params.term
  const entry = glossaryTerms[slug]
  if (!entry) {
    return { title: 'Term Not Found — Crypto Glossary | Sonar Tracker' }
  }
  return {
    title: `What Is ${entry.term}? — Crypto Glossary`,
    description: entry.definition.substring(0, 152) + '...',
    keywords: `${entry.term.toLowerCase()}, ${entry.term.toLowerCase()} meaning, ${entry.term.toLowerCase()} crypto, crypto glossary, blockchain terms`,
    alternates: { canonical: `https://www.sonartracker.io/glossary/${slug}` },
    openGraph: {
      title: `What Is ${entry.term}? — Crypto Glossary | Sonar Tracker`,
      description: entry.definition.substring(0, 152) + '...',
      url: `https://www.sonartracker.io/glossary/${slug}`,
      type: 'article',
    },
  }
}

export async function generateStaticParams() {
  return Object.keys(glossaryTerms).map(term => ({ term }))
}

export default function GlossaryTermPage({ params }) {
  const slug = params.term
  const entry = glossaryTerms[slug]

  if (!entry) {
    return (
      <div style={{ minHeight: '100vh', background: '#0a1621', color: '#e8edf2', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ textAlign: 'center' }}>
          <h1 style={{ fontSize: '2rem', marginBottom: '1rem' }}>Term not found</h1>
          <Link href="/glossary" style={{ color: '#36a6ba' }}>Back to Glossary</Link>
        </div>
      </div>
    )
  }

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'DefinedTerm',
    name: entry.term,
    description: entry.definition,
    inDefinedTermSet: { '@type': 'DefinedTermSet', name: 'Sonar Tracker Crypto Glossary', url: 'https://www.sonartracker.io/glossary' },
  }

  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.sonartracker.io/' },
      { '@type': 'ListItem', position: 2, name: 'Glossary', item: 'https://www.sonartracker.io/glossary' },
      { '@type': 'ListItem', position: 3, name: entry.term, item: `https://www.sonartracker.io/glossary/${slug}` },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
      <div style={{ minHeight: '100vh', background: '#0a1621', color: '#e8edf2', fontFamily: "'Inter', -apple-system, sans-serif" }}>
        <div style={{ maxWidth: '800px', margin: '0 auto', padding: '8rem 2rem 4rem' }}>
          {/* Breadcrumb */}
          <nav style={{ marginBottom: '2rem', fontSize: '0.85rem', color: '#6b7d8f' }}>
            <Link href="/" style={{ color: '#6b7d8f', textDecoration: 'none' }}>Home</Link>
            <span style={{ margin: '0 0.5rem' }}>/</span>
            <Link href="/glossary" style={{ color: '#6b7d8f', textDecoration: 'none' }}>Glossary</Link>
            <span style={{ margin: '0 0.5rem' }}>/</span>
            <span style={{ color: '#36a6ba' }}>{entry.term}</span>
          </nav>

          <h1 style={{ fontSize: '2.5rem', fontWeight: 800, marginBottom: '2rem', background: 'linear-gradient(135deg, #36a6ba, #5dd5ed)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
            What Is {entry.term}?
          </h1>

          <div style={{ fontSize: '1.1rem', lineHeight: 1.8, color: '#c0cad4', marginBottom: '3rem' }}>
            {entry.definition}
          </div>

          {/* Related Terms */}
          {entry.related && entry.related.length > 0 && (
            <div style={{ marginBottom: '3rem' }}>
              <h2 style={{ fontSize: '1.3rem', fontWeight: 700, color: '#e8edf2', marginBottom: '1rem' }}>Related Terms</h2>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {entry.related.map(r => {
                  const relEntry = glossaryTerms[r]
                  if (!relEntry) return null
                  return (
                    <Link key={r} href={`/glossary/${r}`}
                      style={{ display: 'inline-block', padding: '0.5rem 1rem', background: 'rgba(54,166,186,0.1)', border: '1px solid rgba(54,166,186,0.2)', borderRadius: '8px', color: '#36a6ba', textDecoration: 'none', fontSize: '0.9rem', fontWeight: 500 }}>
                      {relEntry.term}
                    </Link>
                  )
                })}
              </div>
            </div>
          )}

          {/* CTA */}
          <div style={{ background: 'rgba(54,166,186,0.08)', border: '1px solid rgba(54,166,186,0.2)', borderRadius: '16px', padding: '2rem', textAlign: 'center' }}>
            <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#e8edf2', marginBottom: '0.75rem' }}>Track whale activity in real-time</h3>
            <p style={{ color: '#8a9bb0', fontSize: '0.95rem', marginBottom: '1rem' }}>See {entry.term.toLowerCase()} patterns as they happen on Sonar Tracker.</p>
            <Link href="/subscribe" style={{ display: 'inline-block', padding: '0.75rem 1.5rem', borderRadius: '8px', background: 'linear-gradient(135deg, #36a6ba, #2d8a9a)', color: '#fff', fontWeight: 700, textDecoration: 'none', fontSize: '0.9rem' }}>Start Tracking — Free</Link>
          </div>

          {/* Back link */}
          <div style={{ marginTop: '2rem', textAlign: 'center' }}>
            <Link href="/glossary" style={{ color: '#36a6ba', textDecoration: 'none', fontSize: '0.9rem' }}>
              ← Back to full glossary
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}
